<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>{{ $title ?? 'Documents Report' }}</title>
    <style>
      @page {
        margin: 18px 18px 22px 18px;
      }
      body {
        font-family: DejaVu Sans, Arial, sans-serif;
        font-size: 10px;
        color: #111827;
      }
      .header {
        margin-bottom: 12px;
      }
      .title {
        font-size: 16px;
        font-weight: 700;
        margin: 0 0 4px 0;
      }
      .meta {
        font-size: 10px;
        color: #374151;
        margin: 0;
      }
      table {
        width: 100%;
        border-collapse: collapse;
        table-layout: fixed;
      }
      thead {
        display: table-header-group;
      }
      th, td {
        border: 1px solid #E5E7EB;
        padding: 6px 6px;
        vertical-align: top;
        word-wrap: break-word;
      }
      th {
        background: #F3F4F6;
        font-weight: 700;
        text-align: left;
      }
      td.num {
        text-align: right;
        white-space: nowrap;
      }
      .footer {
        margin-top: 10px;
        font-size: 9px;
        color: #6B7280;
      }
    </style>
  </head>
  <body>
    <div class="header">
      <p class="title">{{ $title ?? 'Documents Report' }}</p>
      <p class="meta">
        Date generated:
        {{ ($generatedAt ?? now())->format('Y-m-d H:i') }}
      </p>
    </div>

    <table>
      <thead>
        <tr>
          @foreach(($columns ?? []) as $key => $label)
            <th>{{ $label }}</th>
          @endforeach
        </tr>
      </thead>
      <tbody>
        @foreach(($rows ?? []) as $row)
          <tr>
            @foreach(($columns ?? []) as $key => $label)
              @php
                $value = $row->{$key} ?? '';
                if ($key === 'date' || $key === 'date_out') {
                    $value = $value ? \Carbon\Carbon::parse($value)->format('Y-m-d') : '';
                }
                if ($key === 'amount') {
                    $value = ($value !== null && $value !== '') ? number_format((float) $value, 2, '.', '') : '';
                }
              @endphp

              @if($key === 'amount')
                <td class="num">{{ $value }}</td>
              @else
                <td>{{ (string) $value }}</td>
              @endif
            @endforeach
          </tr>
        @endforeach
      </tbody>
    </table>

    <div class="footer">
      <div>Generated by City Hall Monitoring System</div>
    </div>
  </body>
</html>

